#!/usr/bin/env perl

use strict;
use warnings;
use IO::Socket::SSL;
use Getopt::Long;

my $raddress = '';
my $rport = 10041;
my ($host, $service, $state, $recipient);

sub usage {
    print "`nagastc` takes the following options:
--raddress <remotehost>    (required)
--rport <remoteport>       (optional, defaults to 10041)
--host <nagioshost>        (required)
--service <nagiosservice>  (optional)
--state <nagiosstate>      (required)
--to <whotocall>           (required)
\n";
    exit;
}

my $optres = GetOptions(
    "rport=i" => \$rport,
    "raddress=s" => \$raddress,
    "host=s" => \$host,
    "service=s" => \$service,
    "state=s" => \$state,
    "to=s" => \$recipient,
    );

if (!defined($recipient) || $recipient eq '' ||
    !defined($state) || $state eq '' ||
    !defined($host) || $host eq '') {
    usage();
}

my ($v_mode, $sock, $buf);

if(!($sock = IO::Socket::SSL->new( PeerAddr => $raddress,
        PeerPort => $rport,
        Proto    => 'tcp',
    ))) {
    warn "Unable to connect to ".$raddress:.":".$rport.": ", &IO::Socket::SSL::errstr, "\n";
    exit(0);
}

print $sock "NEWCALL $recipient\n";
print $sock "HOST $host\n";
print $sock "SERVICE $service\n" if (defined($service) && $service ne '');
print $sock "STATE $state\n";
print $sock "\n";
